### ISSUE TITLE
The note is deleted when you rotate the screen if it is empty

### ISSUE THREAD

**Issue by Nikitosiki** [Efimj/Shkiper#2]
If you are in the note creation window and you have an empty page (no title and text), and you flip the screen. The note will be deleted as if you were exiting it.
The problem is that if you set a reminder, it will be deleted. That is, if you create a note and set a reminder on an empty note, and then turn the screen over, the reminder will be deleted.

**Comment by Nikitosiki** [comment]
Is it possible to prevent rotating the screen from deleting a note?

**Comment by Efimj** [comment]
> Is it possible to prevent deleting a note by rotating the screen?

In the next update this behavior will be changed, the user will be taken back a screen
Thanks for reporting!
