### ISSUE TITLE
Discord Server [Request]

### ISSUE THREAD

**Issue by Soham52** [Efimj/Shkiper#49]
Maybe make a discord server so people could connect more easily for resolving issues, discuss, etc

Also, thanks for making such a great app ^^

**Comment by Efimj** [comment]
Hi 👋, I'm glad to hear that you liked the app.  in fact, I already have a telegram chat for this, I just haven’t had time to add it to Shkiper yet. In this update I plan to add it to the app 💫

I'll wait for you there 💜:
https://t.me/efim_mobile_projects

**Comment by Soham52** [comment]
Oh that's really nice, thanks 👍
