### ISSUE TITLE
Wierd Note Preview 

### ISSUE THREAD

**Issue by Soham52** [Efimj/Shkiper#65]
After saving a note where the first few lines are Strike though, "~~" appears in the note preview in the home tab

Screenshots -
Note : ![SmartSelect_20240711-211421_Shkiper.jpg](https://github.com/Efimj/Shkiper/assets/73898737/ac163b44-1e18-45a0-95b3-828cced68b73)

Home Tab : ![SmartSelect_20240711-211131_Shkiper.jpg](https://github.com/Efimj/Shkiper/assets/73898737/bbfdd301-3360-4caa-99af-c4f91a054b2b)

**Comment by Efimj** [comment]
Thanks, I'll fix it in the next update 💫

**Comment by Soham52** [comment]
Bro... How are you this fast??? 😮
